/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototype1;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**

 @author John
 */
public class PanelTest extends javax.swing.JFrame
{

   /**
    Creates new form PanelTest
    */
   public PanelTest()
   {
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jTabbedPane4 = new javax.swing.JTabbedPane();
      jPanel2 = new javax.swing.JPanel();
      textField1 = new java.awt.TextField();
      jLabel5 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      textField2 = new java.awt.TextField();
      textField3 = new java.awt.TextField();
      jScrollPane4 = new javax.swing.JScrollPane();
      SampleTable = new javax.swing.JTable();
      jToggleButton1 = new javax.swing.JToggleButton();
      jScrollPane3 = new javax.swing.JScrollPane();
      table1 = new javax.swing.JTable();
      jLabel4 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu2 = new javax.swing.JMenu();
      jMenu3 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      textField1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            textField1ActionPerformed(evt);
         }
      });

      jLabel5.setText("Number of Samples");

      jLabel2.setText("Starting Year");

      jLabel1.setText("Ending Year");

      textField2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            textField2ActionPerformed(evt);
         }
      });

      textField3.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            textField3ActionPerformed(evt);
         }
      });

      SampleTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][]
         {

         },
         new String []
         {
            "Sample Name"
         }
      ));
      jScrollPane4.setViewportView(SampleTable);

      jToggleButton1.setText("OK");
      jToggleButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jToggleButton1ActionPerformed(evt);
         }
      });

      jScrollPane3.setName(""); // NOI18N

      table1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][]
         {
            {null, null, null}
         },
         new String []
         {
            "Year", "Event ", "New Event "
         }
      ));
      jScrollPane3.setViewportView(table1);

      jLabel4.setText("Sample Information");

      jLabel3.setText("ERROR");
      jLabel3.setEnabled(false);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jToggleButton1)
               .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5)
               .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel1))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel4)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(jLabel1))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jToggleButton1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane4))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)))
            .addContainerGap())
      );

      jTabbedPane4.addTab("Sample Data", jPanel2);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 575, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 618, Short.MAX_VALUE)
      );

      jTabbedPane4.addTab("File Meta Data", jPanel1);

      jMenu2.setText("File");
      jMenuBar1.add(jMenu2);

      jMenu3.setText("Edit");
      jMenuBar1.add(jMenu3);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTabbedPane4)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTabbedPane4)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void textField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField1ActionPerformed
   {//GEN-HEADEREND:event_textField1ActionPerformed

   }//GEN-LAST:event_textField1ActionPerformed

   private void textField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField2ActionPerformed
   {//GEN-HEADEREND:event_textField2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_textField2ActionPerformed

   private void textField3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textField3ActionPerformed
   {//GEN-HEADEREND:event_textField3ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_textField3ActionPerformed

   private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton1ActionPerformed
   {//GEN-HEADEREND:event_jToggleButton1ActionPerformed
      // TODO add your handling code here:
      int Start, End, SampleNum;
      jLabel3.setVisible(false);
      if(!textField1.getText().isEmpty() && !textField3.getText().isEmpty() && !textField2.getText().isEmpty())
      {
         Start = Integer.parseInt(textField3.getText());
         End = Integer.parseInt(textField2.getText());
         SampleNum = Integer.parseInt(textField1.getText());
         DefaultTableModel dtm = (DefaultTableModel) table1.getModel();
         if((Start - End) >= 0 )
         dtm.setRowCount((Start - End) + 1 );
         else
         {
            jLabel3.setVisible(true);
            jLabel3.setText("Cannot have starting year before ending year");
         }
         table1.setModel(dtm);
         //table1.
         DefaultTableModel dtm2 = (DefaultTableModel) SampleTable.getModel();
         dtm2.setRowCount(SampleNum );
      }

      TableColumn column = table1.getColumnModel().getColumn(2);

      JComboBox comboBox = new JComboBox();
      comboBox.addItem("Snowboarding");
      comboBox.addItem("Rowing");
      comboBox.addItem("Chasing toddlers");
      comboBox.addItem("Speed reading");
      comboBox.addItem("Teaching high school");
      comboBox.addItem("None");
      column.setCellEditor(new DefaultCellEditor(comboBox));
      DefaultTableCellRenderer renderer =
      new DefaultTableCellRenderer();
      renderer.setToolTipText("Click for combo box");
      column.setCellRenderer(renderer);
   }//GEN-LAST:event_jToggleButton1ActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(PanelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(PanelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(PanelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(PanelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new PanelTest().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTable SampleTable;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JTabbedPane jTabbedPane4;
   private javax.swing.JToggleButton jToggleButton1;
   private javax.swing.JTable table1;
   private java.awt.TextField textField1;
   private java.awt.TextField textField2;
   private java.awt.TextField textField3;
   // End of variables declaration//GEN-END:variables
}
